version: "3.9"
services:
  spring-demo-docker20 :
    build: .
    ports:
      - 8080:8080

  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=scheduledb
    ports:
      - "3307:3306"